Single Linear Regression

In [3]:
import numpy as np
age=np.array([6,8,7,5,10,9,3]).reshape((-1,1))
height=np.array([3.2,4.1,3.6,3.0,4.2,4.1,2.7])
print(age)
print(height)

[[ 6]
 [ 8]
 [ 7]
 [ 5]
 [10]
 [ 9]
 [ 3]]
[3.2 4.1 3.6 3.  4.2 4.1 2.7]


In [4]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(age,height)
model=LinearRegression().fit(age,height)
rsq=model.score(age,height)
print("Co-Efficient of determination: ",rsq)

Co-Efficient of determination:  0.942472354890065


In [5]:
print("Intercept: ",model.intercept_)
print("Slope: ",model.coef_)

Intercept:  1.8934426229508206
Slope:  [0.24262295]


In [10]:
ypre=model.intercept_+model.coef_*age
print("Predicate Response: ",ypre, sep='\n')

Predicate Response: 
[[3.34918033]
 [3.83442623]
 [3.59180328]
 [3.10655738]
 [4.31967213]
 [4.07704918]
 [2.62131148]]


Single Linear Regression without readymade functions

In [11]:
import pandas as pd
age_height={
    "Age":[6,8,7,5,10,9,3],
    "Height":[3.2,4.1,3.6,3.0,4.2,4.1,2.7]
}
df=pd.DataFrame(age_height)
sum_x=df["Age"].sum()
sum_y=df["Height"].sum()
sum_x2=(df["Age"]**2).sum()
sum_xy=(df["Age"]*df["Height"]).sum()
intercept=(sum_y*sum_x2 - sum_x*sum_xy)/(len(df)*sum_x2 - sum_x**2)
slope=(len(df)*sum_xy - sum_x*sum_y)/(len(df)*sum_x2 - sum_x**2)
print("Intercept: ",intercept,"\nSlope: ",slope)

Intercept:  1.8934426229508272 
Slope:  0.2426229508196714


In [12]:
y=slope*(4) + intercept
print("Predicted Value: ",y)

Predicted Value:  2.8639344262295126
